/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.10
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.Mvc.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;

namespace SitefinityWebApp.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "FlightData_MVC", Title = "Space X Latest Flight", SectionName = "Custom")]
	public class FlightDataController : Controller, IPersonalizable
	{
		// GET: FlightData
		public ActionResult Index()
		{
			var model = new FlightDataModel();
			var viewModel = model.GetViewModel();
			return View("Index", viewModel);
		}

		protected override void HandleUnknownAction(string actionName)
		{
			this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
		}

		public string Message { get; set; }
	}
}