/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.10
</auto-generated>
------------------------------------------------------------------------------ */

using Progress.Sitefinity.Renderer.Designers.Attributes;
using Progress.Sitefinity.Renderer.Entities.Content;
using SitefinityWebApp.Mvc.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;
using Telerik.Sitefinity.Data;
using Telerik.Sitefinity.Model;
using System.ComponentModel;

namespace SitefinityWebApp.Mvc.Controllers
{
	[ControllerToolboxItem(Name = "Demo", Title = "Demo Autogenerated", SectionName = "CustomWidgets")]
	public class DemoController : Controller, IPersonalizable
	{
		[Content(Type = "Telerik.Sitefinity.DynamicTypes.Model.Meettheteam.Office", LiveData = true)]
		[DisplayName("Select offices")]
		public MixedContentContext Offices { get; set; }
		
		// GET: Demo
		public ActionResult Index()
		{
			var model = new DemoModel();
			
			return View(model.GetOfficesViewModel(Offices));
		}
		
        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

	}
}